pipeline {
    agent { node { label 'swarm-ci' } }

    stages {


        stage("Build") {
            steps {
               echo 'Build application'
            }
        }

        stage("Test") {
            steps {
                echo 'Test application'
            }
        }    
        stage("Deploy") {
            steps {
                echo 'Deploy application'
            }
        }
            post {
                always {
                 echo 'post'
                }
            }
     }
}